### ISSUE TITLE
Getting this error while executing the code.

### ISSUE THREAD

**Issue by sks147** [aryaminus/saram#2]
```
OCR tool: <module 'pyocr.tesseract' from '/home/btp/anaconda2/lib/python2.7/site-packages/pyocr/tesseract.pyc'>
OCR selected language: ENG (available: osd, equ, eng)
Traceback (most recent call last):
  File "main.py", line 183, in <module>
    s.main(path) # Def main to path
  File "main.py", line 129, in main
    degrees = self.get_rotation_info(image_file_name)
  File "main.py", line 90, in get_rotation_info
    stdoutdata = subprocess.getoutput('tesseract' + arguments % filename)
AttributeError: 'module' object has no attribute 'getoutput'
```

**Comment by aryaminus** [comment]
You are using python 2.7 whereas  subprocess.getoutput is only available in >=3.x . Will update for older version if I find an alternative

**Comment by sks147** [comment]
Issue resolved. Alternative to subprocess is "commands" in python 2.x.
